"""
.. _ref_dataframe_example:

Create and manipulate a DPF Dataframe
=====================================
In this script a Dataframe is generated by extracting a result from a static simulation.
It then showcases different Dataframe viewing and manipulation possibilities.
"""

###############################################################################
# Perform required imports
# ------------------------
# Perform required imports. # This example uses a supplied file that you can
# get by importing the DPF ``examples`` package.

from ansys.dpf import post
from ansys.dpf.post import examples

###############################################################################
# Get the ``Simulation`` object
# -----------------------------
# Get the ``Simulation`` object that allows access to the result. The ``Simulation``
# object must be instantiated with the path for the result file. For example,
# ``"C:/Users/user/my_result.rst"`` on Windows or ``"/home/user/my_result.rst"``
# on Linux.

example_path = examples.download_crankshaft()
# to automatically detect the simulation type, use:
simulation = post.load_simulation(example_path)

# to enable auto-completion, use the equivalent:
simulation = post.StaticMechanicalSimulation(example_path)

# print the simulation to get an overview of what's available
print(simulation)

# Get a ``Dataframe`` object
# --------------------------
# Extract a result as a Dataframe
displacement_dataframe = simulation.displacement(all_sets=True)

# The Dataframe is displayed as a table, with row and column labels to identify the data.
print(displacement_dataframe)

# Explore ``Index`` objects
# -------------------------
# The data labels are each defined by an Index object or one of its specialized subtypes.

# The Dataframe's column labels are defined in Dataframe.columns.
print(displacement_dataframe.columns)

# A ``ResultIndex`` index defines the result stored in the Dataframe.
print(displacement_dataframe.columns[0])
# print(displacement_dataframe.columns.results_index)  # equivalent
# You can check values available for an Index
print(displacement_dataframe.columns[0].values)

# A ``SetIndex`` index defines the available set IDs available.
# A set ID is a unique identifier associated to each time-step, step and sub-step, or frequency
# available in a simulation.
# As shown next, an Index has a name and a list of values of a given type.
print(displacement_dataframe.columns[1])
print(displacement_dataframe.columns[1].values)

# The Dataframe's row labels are defined in Dataframe.index.
print(displacement_dataframe.index)

# A ``MeshIndex`` defines the mesh entities for which data is available.
# It can store node IDs, element IDs, or face IDs.
print(displacement_dataframe.index[0])
# print(displacement_dataframe.index.mesh_index)  # equivalent
# Since the list of possible values can be long and querying it can be costly,
# the list of available values may not be determined unless explicitly asked.
print(displacement_dataframe.index[0].values)
# The ``MeshIndex`` will then be updated to display the actual number of entities available.
print(displacement_dataframe.index[0])
# IMPORTANT: Note that the mesh entity IDs ordered based on the internal data storage structure,
# they are not by ascending order by default!

# A ``CompIndex`` defines the result components for which data is available
print(displacement_dataframe.index[1])
print(displacement_dataframe.index[1].values)

# Change the Dataframe print
# --------------------------
# Options exist to configure the way a Dataframe is displayed.
# You can change the number of data rows displayed
displacement_dataframe.display_max_rows = 9
print(displacement_dataframe)
# Or the number of data columns displayed
displacement_dataframe.display_max_columns = 2
print(displacement_dataframe)
# Notice that the ``...`` symbols specify that the Dataframe is truncated in that direction.

# The special case of ElementalNodal results
# ------------------------------------------
# When dealing with results located on each node of each element (aka. ElementalNodal),
# an ``ElementNodeIndex`` index is added at creation to specify the node number in the
# element's connectivity.
stress = simulation.stress()
print(stress)
print(stress.columns)
