exclude: |
    (?x)^(
        doc/styles/
    )
repos:
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [
    "--profile", "black",
    "--force-sort-within-sections",
    "--skip-glob", "*__init__.py",
    ]

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    args: [
      "--ignore-words",
      "doc/styles/config/vocabularies/ANSYS/accept.txt",
      "doc src",
      "*.py *.rst *.md",
    ]
    exclude: conf.py

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    exclude: ^(tests|examples)/
    args:
      # http://www.pydocstyle.org/en/latest/error_codes.html
      - --ignore=D203,D213,D401,D404,D406,D413

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements

-   repo: https://github.com/ansys/pre-commit-hooks
    rev: v0.4.4
    hooks:
    -   id: add-license-headers
        args:
        -   --start_year=2020

# this validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.21.0
  hooks:
    - id: check-github-workflows
