repos:
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: [
    "--profile", "black",
    "--force-sort-within-sections",
    "--skip-glob", "*__init__.py",
    ]

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.1
  hooks:
  - id: codespell
    args: [
      "docs src",
      "*.py *.rst *.md",
    ]

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    exclude: ^(tests|examples)/
    args:
      # http://www.pydocstyle.org/en/latest/error_codes.html
      - --ignore=D203,D213,D401,D404,D406,D413

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements

# this validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.17.1
  hooks:
    - id: check-github-workflows
