name: "Build DPF Package"
description: "Builds the DPF package"
inputs:
  PACKAGE_NAME:
    description: "Package name"
    required: true
  UPLOAD_WHEELHOUSE:
    description: "Whether to upload the wheelhouse"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: "Upload Docstring Test Results"
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.PACKAGE_NAME }}_doctest
        path: junit/test-doctests-results.xml

    - name: "Upload Test Results"
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.PACKAGE_NAME }}_pytest
        path: tests/junit/test-results.xml

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2