name: "Build and Test"
description: "Builds and Tests the package"
inputs:
  python_version:
    description: "Python version"
    required: true
    default: "3.8"
  ANSYS_VERSION:
    description: "Ansys release version number in the format 221"
    required: true
  PACKAGE_NAME:
    description: "Package name"
    required: true
  MODULE:
    description: "Module name"
    required: true
    default: post
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: ${{ env.python_version }}

    - id: install-dpf
      uses: pyansys/pydpf-actions/install-dpf-server@v1
      with:
        dpf-standalone-TOKEN: ${{secrets.DPF_PIPELINE}}
        ANSYS_VERSION : ${{env.ANSYS_VERSION}}

    - name: Install package
      shell: cmd
      run: |
        pip install -r requirements_build.txt
        python setup.py bdist_wheel
        FOR /F %%a in ('dir /s/b dist\*.whl') do SET WHEELPATH=%%a
        ECHO %WHEELPATH%
        cd tests
        pip install %WHEELPATH%

    - name: Test import
      shell: cmd
      working-directory: tests
      run: python -c "from ansys.dpf import ${{env.MODULE}}; print(${{env.MODULE}}.Report(gpu=False))"

    - name: Check licences of packages
      shell: cmd
      run: |
        pip install pip-licenses
        pip-licenses
        pip uninstall -y pip-licenses

    - name: Retrieve package version
      shell: cmd
      run: |
        echo "::set-output name=VERSION::$(python -c "from ansys.dpf.${{env.MODULE}} import __version__; print(__version__)")"
        echo "PyDPF-Post version is: $(python -c "from ansys.dpf.${{env.MODULE}} import __version__; print(__version__)")"
      id: version

    - name: Upload wheel to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}-v${{ steps.version.outputs.VERSION }}_wheel
        path: ./dist/*

    - name: Install OpenGL
      shell: pwsh
      run: |
        Set-StrictMode -Version Latest
        $ErrorActionPreference = "Stop"
        $PSDefaultParameterValues['*:ErrorAction']='Stop'
        git clone --depth 1 https://github.com/pyvista/gl-ci-helpers.git
        powershell gl-ci-helpers/appveyor/install_opengl.ps1

    - name: Install test offscreen rendering
      shell: bash
      run: |
        .ci/setup_headless_display.sh
        pip install -r .ci/requirements_test_xvfb.txt
        python .ci/display_test.py

    - name: Install Test Environment
      shell: cmd
      run: |
        pip install -r requirements_test.txt
      if: always()

    - name: Test API Docstrings
      shell: cmd
      run: |
         pytest --doctest-modules --junitxml=junit/test-doctests-results.xml ansys/dpf/${{env.MODULE}}

    - name: Kill all servers
      shell: cmd
      run: |
        tasklist /FI "IMAGENAME eq Ans.Dpf.Grpc.exe" 2>NUL | find /I /N "Ans.Dpf.Grpc.exe">NUL
        ECHO %ERRORLEVEL%
        if "%ERRORLEVEL%"=="0"(taskkill /f /im Ans.Dpf.Grpc.exe)
      continue-on-error: true

    - name: Publish Doc Test Results
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}_doctest
        path: junit/test-doctests-results.xml
      if: always()

    - name: Test API
      shell: cmd
      run: |
        cd tests
        pytest --log-level=ERROR --junitxml=junit/test-results.xml --reruns 2 .

    - name: Kill all servers
      shell: cmd
      run: |
        tasklist /FI "IMAGENAME eq Ans.Dpf.Grpc.exe" 2>NUL | find /I /N "Ans.Dpf.Grpc.exe">NUL
        ECHO %ERRORLEVEL%
        if "%ERRORLEVEL%"=="0"(taskkill /f /im Ans.Dpf.Grpc.exe)
      continue-on-error: true

    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}_pytest
        path: tests/junit/test-results.xml
      if: always()