# azure pipelines build and test DPF-Post

variables:
  ALLOW_PLOTTING: true
  package_name: ansys-dpf-post
  SHELLOPTS: 'errexit:pipefail'

trigger:
  branches:
    include:
    - '*'
    exclude:
    - gh-pages
  tags:
    include:
    - '*'

pr:
  branches:
    exclude:
    - '*'

jobs:
- job: DocumentationLinux
  variables:
    python.version: '3.7'  # due to VTK 8.1.2 requirement for docbuild
    PYANSYS_OFF_SCREEN: True
    DPF_PORT: 50055
    TEMP: $(System.DefaultWorkingDirectory)/temp
    AWP_ROOT221: $(System.DefaultWorkingDirectory)/server/v221
    GH_DOC_BRANCH: 'gh-pages'
    
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
    - template: templates\prepare-environment-linux.yml

    - script: |
        pip install -r requirements_docs.txt
      displayName: Install documentation packages for Python

    - script: |
        sphinx-apidoc -o docs/source/api ansys -f --implicit-namespaces --separate --no-headings
        xvfb-run make -C docs html SPHINXOPTS="-w build_errors.txt -N"
      displayName: Build Documentation

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/docs/_build' 
        includeRootFolder: false 
        archiveType: 'zip'
        archiveFile: '$(System.DefaultWorkingDirectory)/docs/archive/doc-ansys-dpf-post.zip'
        replaceExistingArchive: true 
      displayName: 'DOCUMENTATION: zip artifacts'
    
    - task: PublishBuildArtifacts@1
      displayName: 'DOCUMENTATION: publish artifacts'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/docs/archive'
        ArtifactName: doc-ansys-dpf-post
      enabled: true   

    - powershell: |
        git init
        git checkout -b $(GH_DOC_BRANCH)
        git config --global user.name "pyansys-ci-bot"
        git config --global user.email "$(GH_EMAIL)"
        New-Item -ItemType file .nojekyll
        git add .
        git commit -m "Documentation generated by $(Build.DefinitionName)"
      displayName: "Init git and add docs"
      workingDirectory: docs/_build/html

    - script: |
        git remote add origin https://$(GH_PAT)@github.com/pyansys/DPF-Post-docs
        git push -u origin $(GH_DOC_BRANCH) --force
      displayName: "Publish GitHub Pages merge commit"
      workingDirectory: docs/_build/html
      condition: contains(variables['Build.SourceBranch'], 'refs/tags/')

    - template: templates\kill-servers-linux.yml 
