name: "Generate documentation"
description: "Generates the documentation for the DPF local package"
inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.8"
  ANSYS_VERSION:
    description: "Ansys release version number in the format 221"
    required: true
  PACKAGE_NAME:
    description: "Package name"
    required: true
  MODULE:
    description: "Module name"
    required: true
    default: post
  dpf-standalone-TOKEN:
    description: "Token for DPF installation"
    required: true
  install_extras:
    description: "Extras to install for the local package"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Setup Python"
      uses: actions/setup-python@v2.1.4
      with:
        python-version: ${{ inputs.python-version }}

    - name: "Install DPF"
      uses: pyansys/pydpf-actions/install-dpf-server@v1
      with:
        dpf-standalone-TOKEN: ${{inputs.dpf-standalone-TOKEN}}
        ANSYS_VERSION : ${{inputs.ANSYS_VERSION}}

    - name: "Install local package"
      shell: bash
      run: |
        pip install -r requirements_build.txt
        python setup.py bdist_wheel
        export WHEEL_NAME=`ls dist/*.whl`
        echo ${WHEEL_NAME}
        pip install ${WHEEL_NAME}
        cd tests

    - name: "Install extras"
      shell: bash
      run: |
        pip install .[${{inputs.install_extras}}]
      if: ${{inputs.install_extras}} != null

    - name: "Test import"
      shell: bash
      working-directory: tests
      run: python -c "from ansys.dpf import ${{inputs.MODULE}}; print(${{inputs.MODULE}}.Report(gpu=False))"

    - name: "Setup headless display"
      uses: pyvista/setup-headless-display-action@v1

    - name: "Install documentation requirements"
      shell: bash
      run: |
        pip install -r requirements_docs.txt

    - name: "Build HTML Documentation"
      shell: bash
      run: |
        export SPHINX_APIDOC_OPTIONS=inherited-members
        sphinx-apidoc -o docs/source/api ansys -f --implicit-namespaces --separate --no-headings
        cd docs/
        make clean
        echo "Making html doc..."
        make html &>log_html.txt
        cd ../

    - name: "Build PDF Documentation"
      shell: bash
      working-directory: docs
      run: |
        sudo apt update
        sudo apt install texlive-latex-extra latexmk
        echo "Making pdf doc..."
        make pdf &>log_pdf.txt

    - name: "Upload Documentation Build log"
      uses: actions/upload-artifact@v2
      with:
        name: doc-${{inputs.PACKAGE_NAME}}-log
        path: docs/*.txt

    - name: "Zip Documentation"
      shell: bash
      run: |
        ls docs/
        7z a -tzip docs/archive/doc-${{inputs.PACKAGE_NAME}}.zip docs/build

    - name: "Upload Documentation"
      uses: actions/upload-artifact@v2
      with:
        name: doc-${{inputs.PACKAGE_NAME}}
        path: docs/archive/doc-${{inputs.PACKAGE_NAME}}.zip

    - name: "Kill all servers"
      shell: bash
      run: |
        echo $0
        if pgrep -x "Ans.Dpf.Grpc" > /dev/null
        then
            pkill -f Ans.Dpf.Grpc.exe || true
        fi