# Build documentation
name: Documentation Build

on: [push, pull_request, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      DISPLAY: ':99.0'
      DPF_IMAGE: 'docker.pkg.github.com/pyansys/dpf-core/dpf:v2021.1'
      DPF_PORT: 32772
      DPF_START_SERVER: FALSE
      DPF_DOCKER: True
      PYANSYS_OFF_SCREEN: True
      MPLBACKEND: 'TKAgg'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.7

      - name: Install, start, and test the virtual framebuffer
        run: |
          chmod +x .ci/setup_headless_display.sh
          .ci/setup_headless_display.sh
          pip install -r .ci/requirements_test_xvfb.txt
          python .ci/display_test.py        

      - name: Install ansys.dpf.post
        run: |
          pip install -r requirements_build.txt
          pip install -e .
          cd tests
          python -c "from ansys.dpf import post; print(post.Report(gpu=False))"
        env:
          DEVOPS_PAT: ${{ secrets.DEVOPS_PACKAGES_PAT }}

      - name: Copy ansys.dpf.core examples to local directory
        run: |
          EXAMPLES_DIR=$(python -c "from ansys.dpf.core import examples; import os; print(os.path.dirname(examples.__file__))")
          mkdir -p ansys/dpf/core
          cp -r $EXAMPLES_DIR ansys/dpf/core

      - name: Pull, launch, and validate DPF service
        run: |
          echo $PAT | docker login -u $GH_USERNAME --password-stdin docker.pkg.github.com
          touch log.txt
          docker run --restart always --name dpf -v `pwd`:/dpf -v /tmp:/dpf/_cache -p $DPF_PORT:50054 $DPF_IMAGE > log.txt &
          grep -q 'server started on ip' <(timeout 60 tail -f log.txt)
          python -c "from ansys.dpf.post import examples;from ansys.dpf import core;print(core.Model(examples.simple_bar))"
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          PAT: ${{ secrets.REPO_DOWNLOAD_PAT }}

      - name: Build Documentation
        run: |
          sudo apt-get install pandoc -qy
          pip install -r requirements_docs.txt
          make -C docs html
          touch docs/_build/html/.nojekyll
  
      - name: Upload Documentation
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Documentation
          path: docs/_build/html
          retention-days: 7

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_build/html
          CLEAN: true
