name: docs # zizmor: ignore[concurrency-limits] , this is a reusable workflow

on:
# Can be called by the CI
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: "3.10"
      ANSYS_VERSION:
        required: false
        type: string
      standalone_suffix:
        description: "Suffix of the branch on standalone"
        required: false
        type: string
        default: ''
      event_name:
        description: "Name of event calling"
        required: true
        type: string
        default: ''
      generate_pdf:
        description: "Whether to build the PDF doc"
        type: string
        default: 'True'
      debug:
        description: "Debug verbose mode"
        type: string
        default: 'True'
    secrets:
      LICENSE_SERVER:
        required: true
      PYANSYS_CI_BOT_TOKEN:
        required: true
# Can be called manually
  workflow_dispatch:
    inputs:
      python_version:
        description: "Python interpreter"
        required: true
        type: string
        default: "3.10"
      ANSYS_VERSION:
        description: "ANSYS version"
        required: false
        type: string
      standalone_suffix:
        description: "Suffix of the branch on standalone"
        required: false
        type: string
        default: ''
      generate_pdf:
        description: "Whether to build the PDF doc"
        type: string
        default: 'True'

env:
  PACKAGE_NAME: ansys-dpf-post
  MODULE: post
  DPF_DEFAULT_GRPC_MODE: insecure

permissions: {}

jobs:
  doc-style:
    name: "Check doc style"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required for doc-style action to post comments
    steps:
        - name: "Running documentation style checks"
          uses: ansys/actions/doc-style@7d55ff0b9f67c77dae50a286d711ee1ae27b0a25 # v10.2.12
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

  docs:
    name: "Documentation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Set licensing"
        shell: bash
        env:
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
        run: |
          echo "ANSYS_DPF_ACCEPT_LA=Y" >> $GITHUB_ENV
          echo "ANSYSLMD_LICENSE_FILE=1055@${LICENSE_SERVER}" >> $GITHUB_ENV
          echo "DPF_DEFAULT_GRPC_MODE=insecure" >> $GITHUB_ENV

      - name: "Setup Python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ inputs.python_version }}

      - name: "Install OS packages"
        shell: bash
        run: |
          sudo apt update
          sudo apt install pandoc texlive-latex-extra latexmk

      - name: "Install CI requirements (pydpf-core from main)"
        shell: bash
        run: pip install -r requirements/requirements_ci.txt

      - name: "Build Package"
        id: build-package
        uses: ansys/pydpf-actions/build_package@195207a462b23da5645fde44ac685e81b29035a4 # v2.3
        with:
          python-version: ${{ inputs.python_version }}
          ANSYS_VERSION: ${{ github.event.inputs.ansys_version || vars.ANSYS_VERSION_DEFAULT }}
          PACKAGE_NAME: ${{env.PACKAGE_NAME}}
          MODULE: ${{env.MODULE}}
          dpf-standalone-TOKEN: ${{secrets.PYANSYS_CI_BOT_TOKEN}}
          install_extras: graphics
          wheel: false
          wheelhouse: false
          standalone_suffix: ${{ inputs.standalone_suffix }}

      - name: "Setup headless display"
        uses: pyvista/setup-headless-display-action@5bc8de3bc71fcda7a96439571287a554901541a0 # v4.3

      - name: "Install documentation requirements"
        shell: bash
        run: |
          pip install -r requirements/requirements_docs.txt

      - name: "List installed packages"
        shell: bash
        run: pip list

      - name: "Build sphinx doc"
        shell: bash
        env:
          BUILD_EXTRAS: ${{ inputs.build_extras }}
        run: |
          export SPHINX_APIDOC_OPTIONS=inherited-members
          sphinx-apidoc -o doc/source/api src/ansys ${BUILD_EXTRAS} -f --implicit-namespaces --separate --no-headings $DEBUG_SPHINX

      - name: "Build HTML Documentation"
        shell: bash
        working-directory: doc
        env:
          RUNNER_TEMP: ${{ runner.temp }}
        run: |
          export TEMP=${RUNNER_TEMP}
          make clean
          echo "Making html doc..."
          make html $DEBUG_HTML >> log.txt 2>&1

      - name: "Check for success"
        shell: bash
        working-directory: doc
        run: |
          case `tail -n 5 log.txt | grep -F "build succeeded" >/dev/null; echo $?` in
          0)
            echo "Build succeeded!"
            exit 0;;
          1)
            echo "Documentation generation failed, please check previous step!"
            exit 1;;
          *)
            echo "An error occurred while checking success of the previous step!"
            exit 1;;
          esac

      - name: "Build PDF Documentation"
        shell: bash
        working-directory: doc
        if: ${{ inputs.generate_pdf == 'true' }}
        env:
          RUNNER_TEMP: ${{ runner.temp }}
        run: |
          export TEMP=${RUNNER_TEMP}
          echo "Making pdf doc..."
          make pdf $DEBUG_PDF

      - name: "Upload Documentation Build log"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: doc-${{env.PACKAGE_NAME}}-log
          path: doc/*.txt
        if: always()

      - name: "Zip HTML Documentation"
        uses: vimtor/action-zip@5407800dfb2b1b37d48df912330cb22f4ab6f422 # v1.3
        with:
          files: doc/build/html/
          dest: HTML-doc-${{env.PACKAGE_NAME}}.zip
        if: always()

      - name: "Upload HTML Documentation"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: HTML-doc-${{env.PACKAGE_NAME}}.zip
          path: HTML-doc-${{env.PACKAGE_NAME}}.zip
        if: always()

      - name: "Find PDF Documentation"
        shell: bash
        if: ${{ inputs.generate_pdf == 'true' }}
        id: pdf
        working-directory: doc/build/latex
        run: |
          pattern="PyDPF-*.pdf"
          files=( $pattern )
          echo "PDF_file=${files[0]}" >> $GITHUB_OUTPUT
          echo "Found PDF doc: ${files[0]}"

      - name: "Zip PDF Documentation"
        uses: vimtor/action-zip@5407800dfb2b1b37d48df912330cb22f4ab6f422 # v1.3
        if: ${{ inputs.generate_pdf == 'true' }}
        with:
          files: doc/build/latex/${{ steps.pdf.outputs.PDF_file }}
          dest: PDF-doc-${{env.PACKAGE_NAME}}.zip

      - name: "Upload PDF Documentation"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: inputs.generate_pdf == 'true'
        with:
          name: PDF-doc-${{env.PACKAGE_NAME}}
          path: PDF-doc-${{env.PACKAGE_NAME}}.zip

      - name: "Kill all servers"
        uses: ansys/pydpf-actions/kill-dpf-servers@195207a462b23da5645fde44ac685e81b29035a4 # v2.3
        if: always()
