name: examples # zizmor: ignore[concurrency-limits] , this is a reusable workflow

on:
# Can be called by the CI
  workflow_call:
    inputs:
      python_versions:
        required: false
        type: string
        default: '["3.10"]'
      ANSYS_VERSION:
        required: false
        type: string
      standalone_suffix:
        description: "Suffix of the branch on standalone"
        required: false
        type: string
        default: ''
    secrets:
      LICENSE_SERVER:
        required: true
      PYANSYS_CI_BOT_TOKEN:
        required: true
# Can be called manually
  workflow_dispatch:
    inputs:
      python_versions:
        description: "Python interpreters to test."
        required: true
        type: string
        default: '["3.10"]'
      ANSYS_VERSION:
        description: "ANSYS version to run."
        required: false
        type: string
      standalone_suffix:
        description: "Suffix of the branch on standalone"
        required: false
        type: string
        default: ''

env:
  PACKAGE_NAME: ansys-dpf-post
  MODULE: post
  DPF_DEFAULT_GRPC_MODE: insecure

permissions: {}

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      python_versions: ${{ steps.set_array.outputs.python_versions }}
    steps:
      - id: set_array
        env:
          PYTHON_VERSIONS: ${{ inputs.python_versions }}
        run: |
          echo "python_versions=${PYTHON_VERSIONS}" >> $GITHUB_OUTPUT

  examples:
    name: "Run Examples"
    needs: setup
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(needs.setup.outputs.python_versions) }}
        os: ["windows-latest", "ubuntu-latest"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Set licensing"
        shell: bash
        env:
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
        run: |
          echo "ANSYS_DPF_ACCEPT_LA=Y" >> $GITHUB_ENV
          echo "ANSYSLMD_LICENSE_FILE=1055@${LICENSE_SERVER}" >> $GITHUB_ENV
          echo "DPF_DEFAULT_GRPC_MODE=insecure" >> $GITHUB_ENV

      - name: "Setup Python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install CI requirements (pydpf-core from main)"
        shell: bash
        run: pip install -r requirements/requirements_ci.txt

      - name: "Build Package"
        uses: ansys/pydpf-actions/build_package@195207a462b23da5645fde44ac685e81b29035a4 # v2.3
        with:
          python-version: ${{ matrix.python-version }}
          ANSYS_VERSION: ${{ github.event.inputs.ansys_version || vars.ANSYS_VERSION_DEFAULT }}
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
          MODULE: ${{ env.MODULE }}
          dpf-standalone-TOKEN: ${{secrets.PYANSYS_CI_BOT_TOKEN}}
          install_extras: graphics
          wheelhouse: false
          wheel: false
          standalone_suffix: ${{ inputs.standalone_suffix }}

      - name: "Prepare Testing Environment"
        uses: ansys/pydpf-actions/prepare_tests@195207a462b23da5645fde44ac685e81b29035a4 # v2.3
        with:
          DEBUG: true

      - name: "List installed packages"
        shell: bash
        run: pip list

      - name: "Run examples"
        shell: bash
        working-directory: .ci
        run: |
          echo on
          python run_examples.py

      - name: "Kill all servers"
        uses: ansys/pydpf-actions/kill-dpf-servers@195207a462b23da5645fde44ac685e81b29035a4 # v2.3
        if: always()
