name: Release

on:
#  pull_request:
#    tags:
#      - "*"
#    branches:
#      - "release*"

  push:
    tags:
      - "*"
    branches:
      - "release*"

env:
  PACKAGE_NAME: ansys-dpf-post
  ANSYS_VERSION: 221
  DPF_ACTIONS_VERSION: fix/versions

jobs:
  Build_Test_Upload:
    name: Build_Test_Upload
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9"]
        os: ["windows-2019", "ubuntu-latest"]

    steps:
      - uses: actions/checkout@v2

      - name: "Build Package"
        uses: pyansys/pydpf-actions/build_package@${{env.DPF_ACTIONS_VERSION}}
        with:
          python-version: ${{ matrix.python-version }}
          ANSYS_VERSION: ${{env.ANSYS_VERSION}}
          PACKAGE_NAME: ${{env.PACKAGE_NAME}}
          MODULE: post
          dpf-standalone-TOKEN: ${{secrets.DPF_PIPELINE}}
          install_extras: plotting

      - id: "Test Package"
        uses: pyansys/pydpf-actions/test_package@${{env.DPF_ACTIONS_VERSION}}
        with:
          MODULE: post

  Documentation:
    name: Documentation
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: "Build Documentation"
        uses: pyansys/pydpf-actions/build_doc@${{env.DPF_ACTIONS_VERSION}}
        with:
          python-version: "3.8"
          ANSYS_VERSION: ${{env.ANSYS_VERSION}}
          PACKAGE_NAME: ${{env.PACKAGE_NAME}}
          MODULE: post
          dpf-standalone-TOKEN: ${{secrets.DPF_PIPELINE}}
          install_extras: plotting
        timeout-minutes: 30

      - name: "Push Documentation"
        uses: pyansys/pydpf-actions/push_doc@${{env.DPF_ACTIONS_VERSION}}
        with:
          PYANSYS_CI_BOT_TOKEN: ${{secrets.PYANSYS_CI_BOT_TOKEN}}
          DOC_REPO: DPF-Post-docs

  Release:
    runs-on: ubuntu-latest
    needs: [Build_Test_Upload, Documentation]
    steps:
      - name: "Release Package"
        uses: pyansys/pydpf-actions/release_package@${{env.DPF_ACTIONS_VERSION}}
        with:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}