name: Release

on:
  release:
    types: [published]

env:
  DOCUMENTATION_CNAME: 'post.docs.pyansys.com'

jobs:

  Publish_to_PyPI:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: "Upload to Public PyPI"
        run: |
          pip install twine
          pip install build
          python -m build
          twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

  upload_docs_release:
    name: "Upload release documentation"
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [Publish_to_PyPI]
    steps:
      - name: Deploy the stable documentation
        uses: pyansys/actions/doc-deploy-stable@v2
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
