name: Release

on:
  release:
    types: [published]

env:
  DOCUMENTATION_CNAME: 'post.docs.pyansys.com'
  PYTHON_MAIN_VERSION: '3.10'

jobs:

  Publish_to_PyPI:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: "Upload to Public PyPI"
        run: |
          pip install twine
          pip install build
          python -m build
          twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}


  upload_docs_release:
    name: "Upload release documentation"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: [Publish_to_PyPI]
    steps:

      - name: "Download Release Asset - HTML"
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          file: HTML-doc-ansys-dpf-post.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Unzip the HMTL documentation"
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq HTML-doc-ansys-dpf-post.zip -d documentation-html

      - name: Deploy the stable documentation
        uses: pyansys/actions/doc-deploy-stable@v4
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

