name: Release

on:
#  pull_request:
#    tags:
#      - "*"
#    branches:
#      - "release*"

  push:
    tags:
      - "*"
    branches:
      - "release*"

env:
  PACKAGE_NAME: ansys-dpf-post
  ANSYS_VERSION: 221

jobs:
  Build_Test_Upload:
    name: Build_Test_Upload
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9"]
        os: ["windows-2019", "ubuntu-latest"]

    steps:
      - uses: actions/checkout@v2

      - id: build_package
        uses: ./.github/build_package
        with:
          python-version: ${{ matrix.python-version }}
          ANSYS_VERSION: ${{env.ANSYS_VERSION}}
          PACKAGE_NAME: ${{env.PACKAGE_NAME}}
          MODULE: post
          dpf-standalone-TOKEN: ${{secrets.DPF_PIPELINE}}
          install_extras: plotting

      - id: test_package
        uses: ./.github/test_package
        with:
          MODULE: post

      - id: upload_package
        uses: ./.github/test_package
        with:
          PACKAGE_NAME: ${{env.PACKAGE_NAME}}
          UPLOAD_WHEELHOUSE: false
        if: ${{ runner.os }} == 'Windows' && ${{ matrix.python-version }} == "3.8"

  Release:
    runs-on: ubuntu-latest
    needs: Build_Test_Upload
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -R

      - name: Install twine
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install setuptools twine

      - name: Build package
        run: python setup.py sdist

      - name: Publish distribution 📦 to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_REPOSITORY_URL: "https://upload.pypi.org/legacy/"
        run: |
          twine upload --skip-existing ./**/*.whl
          twine upload --skip-existing ./**/*.tar.gz
#         /!\ Do NOT publish to Pypi the zip containing the wheelhouses

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./**/*.whl
            ./**/*.tar.gz
            ./**/*.pdf
            ./**/*.zip