# check spelling, codestyle
name: Style Check

on:
  pull_request:
     branches-ignore:
       - '*no-ci*'
       - 'dependabot/*'
  push:
    tags:
      - "*"
    branches:
      - master
      - "release*"
      - 'dependabot/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  style:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.8

      - name: Install style requirements
        run: |
          pip install -r requirements/requirements_style.txt --disable-pip-version-check

      - name: Codespell
        run: |
          make codespell

      - name: flake8
        run: |
          make flake8
